name: Cypress Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v23.11.0

      - name: Install Dependencies
        run: |
          npm ci
          npx cypress install

      - name: Run Cypress Tests
        run: npx cypress run
